# Generated by Django 5.1.3 on 2024-12-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users/default_profile/avatar.jpeg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
