# Generated by Django 5.1.3 on 2024-12-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users/default_profile/avatar-profile.jpg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
